declare const styles: {
  readonly "GeneSymbolValidator": string;
  readonly "chatWindow": string;
  readonly "default": string;
  readonly "empty": string;
  readonly "errorMessage": string;
  readonly "form": string;
  readonly "genesSelection": string;
  readonly "icon": string;
  readonly "input": string;
  readonly "inputarea": string;
  readonly "invalidBubble": string;
  readonly "message": string;
  readonly "multiChoiceLabel": string;
  readonly "noChoiceLabel": string;
  readonly "nowrap": string;
  readonly "oncoprintHeatmap": string;
  readonly "oqlNotice": string;
  readonly "pendingMessage": string;
  readonly "question": string;
  readonly "singleChoiceLabel": string;
  readonly "studyView": string;
  readonly "studyViewFocus": string;
  readonly "suggestionBubble": string;
  readonly "textarea": string;
  readonly "textheader": string;
  readonly "titlearea": string;
  readonly "topRow": string;
  readonly "validBubble": string;
  readonly "validationBubbleBase": string;
};
export = styles;

